name: Fuck app

on:

  push:
    branches:
      - main

  schedule:
  - cron: "59 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
         persist-credentials: false
         fetch-depth: 1

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "aldymerno173@gmail.com"
          git config --local user.name "AldiMeirano"
          git add -A

          arr[0]="feat: create microservicee"
          arr[1]="fix: fix bug in china"
          arr[2]="feat:  create indonesi green"
          arr[3]="feat:  create indonesi green"
          arr[4]="fix: fix bug in china"
          arr[5]="feat:  create indonesi green"
          arr[6]="fix: fix bug in china"
          arr[7]="feat:  create indonesi green"
          arr[8]="fix: fix bug in china"
          arr[9]="feat:  create indonesi green"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
